name: pulsefit_pro # Я оставил имя pulsefit_pro, чтобы не сломались импорты в Dart файлах. Если сменишь на Trainer, придется менять везде 'package:pulsefit_pro/...'
description: Trainer - Your personal AI fitness trainer. Track progress, get personalized workouts, and nutrition advice powered by AI.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0
  flutter_svg: ^2.0.10+1
  shimmer: ^3.0.0
  image_picker: ^1.1.2
  intl: ^0.20.2
  window_manager: ^0.3.9
  http: ^1.2.2
  cached_network_image: ^3.4.1
  video_player: ^2.8.6
  chewie: ^1.7.5
  flutter_dotenv: ^5.1.0
  shared_preferences: ^2.2.2
  permission_handler: ^11.3.1
  flutter_local_notifications: ^17.2.2
  timezone: ^0.9.4
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0
  path: ^1.9.0
  path_provider: ^2.1.2
  url_launcher: ^6.2.2
  mobile_scanner: ^5.2.3
  supabase_flutter: ^2.8.0
  flutter_secure_storage: ^9.2.2
  muscle_selector: ^1.0.4
  share_plus: ^7.2.2
  camera: ^0.11.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_native_splash: ^2.4.6

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/placeholder/profile.jpg
    - assets/images/champ_avatar.jpg
    - assets/images/gwagon.png
    - assets/logo/trainer_mark.png
    - assets/logo/app_logo.png
    - assets/logo/app_logo.jpg
    - secrets.json
    
    # --- MUSCLE ASSETS ---
    # Важно: каждая подпапка должна быть указана отдельно
    - assets/muscles/ 
    - assets/muscles/male/   
    - assets/muscles/female/
    
    - assets/gifs/motivation/m1.gif
    - assets/gifs/motivation/m2.gif

flutter_native_splash:
  color: "#0B0B0F"
  image: assets/logo/trainer_mark.png
  android_12:
    color: "#0B0B0F"
    image: assets/logo/trainer_mark.png
  web: false